### ISSUE TITLE
database for all patients

### ISSUE THREAD

**Issue by beeCwright** [pylidc/pylidc#1]
running qu.all() shows all the id's for 97 patients, but the LIDC dataset has over 1000 patients. Is there an easy way to incorporate the others?

**Comment by notmatthancock** [comment]
Are you referring to the first example in the README where
```
qu = pl.query(pl.Scan).filter(pl.Scan.slice_thickness <= 1)
print(qu.count())
# => 97
```
? In this case, we are querying for all `Scan` objects where the slice thickness attribute is less than 1 millimeter. If you want to query for all Scan objects, you would leave off the filter, i.e.,
```
qu = pl.query(pl.Scan)
print(qu.count())
# => 1018
```
Each scan object has a `patient_id` attribute (which is not necessarily unique since some patients had multiple scans). You can query for a specific patient id by executing (for example):
```
scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == 'LIDC-IDRI-0025').first()
print(scan.patient_id)
# => LIDC-IDRI-0025
```

**Comment by beeCwright** [comment]
ahhhhh wow. yep. sorry.

**Comment by notmatthancock** [comment]
no problem
