### ISSUE TITLE
Include sqlalchemy automatically as dependency

### ISSUE THREAD

**Issue by WGierke** [pylidc/pylidc#8]
Thanks for your very useful library!
Would it make sense to automatically install sqlalchemy as well when pylidc is beeing installed?
Update: when installing dependencies using `pip install -r requirements.txt`, one gets the error `ModuleNotFoundError: No module named 'sqlalchemy'` which isn't even resolved when putting `sqlalchemy` ahead of `pylidc`.

**Comment by notmatthancock** [comment]
Ok, thanks for pointing that out. I'm not sure why it stopped installing dependencies. I built the package as a universal wheel (rather than a source dist as before), and it appears to work now (caveat: I know nearly nothing about python package distribution) after installing from pip on a fresh virtualenv. Try it out, and let me know if it works for you.

**Comment by WGierke** [comment]
Yes, it seems to be fixed in version 0.1.8. Thanks a lot!
