### ISSUE TITLE
to_volume: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 140

### ISSUE THREAD

**Issue by WGierke** [pylidc/pylidc#9]
Hey,
when running
```python
scan = pl.query(pl.Scan).filter(pl.Scan.patient_id == 'LIDC-IDRI-0005').first()
scan.to_volume()
```
I'm getting
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pylidc/Scan.py", line 453, in to_volume
    images.append( dicom.read_file(f) )
  File "/usr/local/lib/python3.5/dist-packages/dicom/filereader.py", line 614, in read_file
    force=force)
  File "/usr/local/lib/python3.5/dist-packages/dicom/filereader.py", line 515, in read_partial
    preamble = read_preamble(fileobj, force)
  File "/usr/local/lib/python3.5/dist-packages/dicom/filereader.py", line 477, in read_preamble
    preamble = fp.read(0x80)
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 140: invalid continuation byte

```

 for all patient DICOM files I tried so far.
Do you see what might be the problem?

**Comment by notmatthancock** [comment]
It works fine in python 2, so it's most likely a py3 issue. I'll look closer when I have a little more time -- probably [somewhere in this area](https://github.com/pylidc/pylidc/blob/44db8ca9c41a62895b81bb4d7a584da0babecd99/pylidc/Scan.py#L301).

**Comment by notmatthancock** [comment]
It was simpler than I thought. The issue was [here](https://github.com/pylidc/pylidc/blob/44db8ca9c41a62895b81bb4d7a584da0babecd99/pylidc/Scan.py#L452), which is [now updated](https://github.com/pylidc/pylidc/blob/a324b6ca4ee78385c8721d13ffe76126e6864979/pylidc/Scan.py#L443). I forgot to update the `to_volume` function to use the `load_all_dicom_images` function (which is more robust due to the fix from #7). Incidentally, the `open` in the old `to_volume` was not using the mode, `'rb'`, which broke python 3 compatibility for this function. The latest is on pip, `pip install --upgrade pylidc`.

**Comment by WGierke** [comment]
Works! Thanks a lot. You're reaction time is breathtaking :)

**Comment by WGierke** [comment]
@notmatthancock It's not an issue but I'm asking for an advice here:
I'd like to save a binary mask of a scan where each pixel is set to 1 if it corresponds to a cancerous annotation. Basically, it should have the shape of `scan.to_volume()` but only consist of `annotation.get_binary_mask()`, padded with `False`. I'm currently struggling with replacing the annotation areas in the volumes with the binary masks. Do you have any suggestions for that? Perhaps you also already encountered that problem? :)
